export class PMItem {
    payment_itm_id: number;
    payment_id: number;
    matdoc_no : string;
    doc_year : string;
    item_status : string;
    matdoc_item : string;
    amount: number;
    movement_type: string;
    mat_no: string;
    mat_desc: string;
    plant: string;
    sloc: string;
    currency: string;
    po_no: string;
    delivery_indicator: string;
    item_text: string;
    good_recipient: string;
    controlling_area: string;
    costcenter: string;
    order_no: string;
    main_asset_no: string;
    sub_asset_no: string;
    comp_code: string;
    wbs_no: string;
    wbs_name: string;
    account_no: string;
    account_name: string;
    gr_qty: number;
    unit: string;
    posting_date: string;
    account_entered_date: string;
    account_entered_time: string;
    user_name: string;
    reference_no: string;
    tcode: string;
    project_name: string;
}  