export const API_BASE_URL: string = 'http://sunpochai.thddns.net:5555'
export const API_TRACKING_LIST: string = API_BASE_URL + '/metronic/preview/inc/api/datatables/demos/default.php'
export const API_COMPANY_LIST: string = API_BASE_URL + '/api/company/list'
export const API_COMPANY_GET: string = API_BASE_URL + '/api/company'
export const API_COMPANY_PUT: string = API_BASE_URL + '/api/company'
export const API_COMPANY_DEL: string = API_BASE_URL + '/api/company'
export const API_COMPANY_INSERT: string = API_BASE_URL + '/api/company/insert' 