export const API_BASE_URL: string = 'http://sunpochai.thddns.net:5555'
export const API_COMPANY_LIST: string = API_BASE_URL + '/api/company/list'
export const API_COMPANY_GET: string = API_BASE_URL + '/api/company'
export const API_COMPANY_PUT: string = API_BASE_URL + '/api/company'
export const API_COMPANY_DEL: string = API_BASE_URL + '/api/company'
export const API_COMPANY_INSERT: string = API_BASE_URL + '/api/company/insert' 

export const API_DOCTYPE_LIST: string = API_BASE_URL + '/api/doctype/list'
export const API_DOCTYPE_GET_PUT_DEL: string = API_BASE_URL + '/api/doctype'
export const API_DOCTYPE_INSERT: string = API_BASE_URL + '/api/doctype/insert'  